spring:
  profiles:
    active:
    - dev  
---
spring:
  profiles: dev
  application:
    name: myspringcloud-config-cjs-dev
---
spring:
  profiles: dev
  application:
    name: myspringcloud-config-cjs-test
#请保存UTF-8格式
